### ISSUE TITLE
We need a logo

### ISSUE THREAD

**Issue by bitboxer** [signdict/website#14]
This is one of the most important things we need right now. The logo
should somehow transport that this project deals with sign language.
With an interesting twist on it. Just a pair of hands is the goto logo
for projects dealing with sign language. I am searching for something
more unique than that.

**Comment by bitboxer** [comment]
I brainstormed with @anikalindtner yesterday and we came up with a hand that has a play button. Like this:

![img_0178](https://cloud.githubusercontent.com/assets/56195/23395487/2e8c85e0-fd8f-11e6-9f87-850c5ae18cdb.jpg)

**Comment by RRorg** [comment]
Played around with a bit, have you already decided on the general style and feel of this project's design? More playful, more serious, more bootstrap-y clean?

![screenshot 2017-02-28 um 17 21 56](https://cloud.githubusercontent.com/assets/11065422/23413936/9103979a-fdda-11e6-8ee6-a2b7a805e744.png)

**Comment by bitboxer** [comment]
I like the first one. Currently I am not sure, but I think I want a modern, sleek look without too much playfulness. But not too boring. A few funny icons here and there to make it a more "personal" experience and not too corporate.

**Comment by bitboxer** [comment]
And thank you for doing this!

**Comment by bitboxer** [comment]
@RRorg do you have a vector version of the first hand (the one in the upper left)? Can you upload it somewhere and link it here? I would love to play around with it a bit.

**Comment by bitboxer** [comment]
@RRorg do you have a vector version of the first hand (the one in the upper left)? Can you upload it somewhere and link it here? I would love to play around with it a bit.

**Comment by RRorg** [comment]
Here you go! :) 

[signdict.ai.zip](https://github.com/signdict/website/files/810038/signdict.ai.zip)

**Comment by EinLama** [comment]
I like the one in the top right most, but the first one is also very nice! :)

**Comment by RRorg** [comment]
The one on the top left looks very organic, so we'd have to be extra careful with colors and integrating it in the overall design as to not look unprofessional (see: 90's-style table-layouted daycare center website logo) - maybe tone down the 'noise' of the lines a bit more ?

Another route I think could be worthwhile to play around with a bit is seeing if there are different hand positions that could be used, like I did with the OK sign in the bottom right. Are there other simple hand poses that are relevant and hopefully not-offensive-across-all-cultures?

**Comment by Rantastique** [comment]
I actually like the third version (left bottom corner) best. 
The first one is also nice, but I also think it should be a little "simplified" (for the reasons @RRorg pointed out).
I'd be very very careful with different hand poses. The last one (the OK sign) could actually be offensive. Doesn't it mean "asshole" in some countries?

Also, just a thought: I know that this isn't about race. Still, it's a point we could think about, especially regarding the current political situation. 
So what about maybe a (for example) green hand instead of a white one?

**Comment by RRorg** [comment]
Good call on the colors - I'd have the logo use a non-skin/non-skin-associated color, if it were my call to make. Something like a subtle green-teal-blue gradient comes to mind, usual modern web style.
Hopefully the palette will be donated together with the design (see issue #15 )

**Comment by RRorg** [comment]
With the offensiveness of the hand signs we probably need to check who's our main target audience. The 🤘 in bodo's photo on the current placeholder page for example is a very common and explicit insult referring to cuckoldry in Italy (and prob other mediterranean regions too) - but I'd still trust the average internet user to see intent & mainstream meaning of the hand signs 😋 

Is there maybe a distinctive signed word we could use as logo - like the gesture for translation, communication, etc? maybe have two hands instead of just one

**Comment by blinry** [comment]
Hey all, I'd like to be involved! :) I've [dabbled a bit](https://morr.cc/tag/logo/) in logo design in the past, and actually did one with a play symbol [quite recently](https://morr.cc/voctocat/)! :) Here's a quick sketch of another idea, which might help to make the viewer curious about the finger alphabet! But it might be too "classical" for @bitboxer? ;)

![alphabet](https://cloud.githubusercontent.com/assets/81277/23473994/86389c2e-feb2-11e6-9b6a-3756c1f0f265.png)

**Comment by blinry** [comment]
My first association was also the ILY gesture! I think it lends itself to a combination with a play icon quite well, and is a little bit more interesting than just an open hand:

![screenshot-2017-03-01_19 17 38](https://cloud.githubusercontent.com/assets/81277/23474376/e30a44ce-feb3-11e6-8371-519dae60dc47.png)

You already started a discussion about the possible offensiveness of this gesture, but I don't think it's a problem in this context. Instead, it seems to be a nice, international (?), inclusive, iconic gesture, which I'd love to embrace! :)

**Comment by blinry** [comment]
Playing around with the "play icon in a TV" idea… This one requires an usual format, and won't be suited for low resolutions. Buy maybe it sparks some more ideas! :)

![screenshot-2017-03-01_19 31 53](https://cloud.githubusercontent.com/assets/81277/23474932/df7d1654-feb5-11e6-9fa2-22e87c8150ca.png)

**Comment by blinry** [comment]
Like this one! :) Its aesthetics are inspired by the YouTube logo. Could also work with the open hand, or any other one-hand gesture, really. Quite recognizable and suited to small sizes.

![screenshot-2017-03-01_19 44 11](https://cloud.githubusercontent.com/assets/81277/23475386/bb9a0e98-feb7-11e6-932f-ea6ea4242a63.png)

**Comment by blinry** [comment]
Well, it's going to be a dictionary, innit? :) This and the previous one could also be combined with a play icon.

![screenshot-2017-03-01_19 56 50](https://cloud.githubusercontent.com/assets/81277/23475930/59fe0db8-feb9-11e6-96a4-c5a0634717f5.png)

**Comment by bitboxer** [comment]
@RRorg I thought in italy the offensive one was the "metal hand", without the thumb? But I am not sure on this one.

@blinry I am open to every suggestion right now and love your contributions. Thank you! Love the brainstorming of different ideas!

**Comment by blinry** [comment]
THUG LIFE style! :D This isn't meant seriously, it's just based on the obversation that there are 2x4 letters in the name.

![screenshot-2017-03-01_20 11 29](https://cloud.githubusercontent.com/assets/81277/23476544/66dbcadc-febb-11e6-93b7-2ee38bc8ff91.png)

**Comment by blinry** [comment]
I think that's it for now. Let me know what you think. GitHub's "reaction" feature (top right of each post) might be well suited to leave some quick feedback to these! :)

@Rantastique, I love that you brought up the issue of colors! My sketches are just for the ideas and visuals, and I agree the hands should probably be colored in a non-skin color, respectively.

**Comment by anikalindtner** [comment]
@blinry i like the ones with the two hands forming the frame a lot, but i agree that it is too detailled for a logo that needs to be recognizable in all sizes. 

the one with the play button on the ILY is a nice idea, but i think that since the hand is already signing something, it would be weird to THEN have a play button on it. the play button usually is on something that can be seen as a canvas - like an open hand or a start button, that is ready to do something. if the button is on a hand that is already in the end position of a sign, that i think would confuse the message of a play button. do you know what i mean? 

and omg hehe thank you for the last one 😂 

i really love the first first hand drawing of @RRorg (upper left corner), i think my hand is a bit too irregular for a logo still, so i agree that the "noise" could be toned down a bit and you can also make the fingers a little bit more regular and the palm of the hand a bit smaller. 

an idea on the total contrary side: i was wondering if it would look nice in a pencil drawing kind of style? like this style: https://img.clipartfox.com/4dcbaf111aeca6730bfecf0a85b46404_gods-praying-hands-drawings-gods-open-hands-clipart_883-904.jpeg 

or this: 

![pencilhand](https://cloud.githubusercontent.com/assets/1711357/23479654/7670fda0-fec5-11e6-81ea-52353bad30d2.png)

WDYT?

**Comment by RRorg** [comment]
+1 on the pencil drawing idea - doesn't need to be too detailed, just some simple lines for more detail and shade, could very well be done in vector too and would give a polished and intentional look if done right

**Comment by Rantastique** [comment]
Whoa, so many great ideas!
I really like the one where there's a hand on a book. And I would love to see how a pencil style logo would work out.

**Comment by bitboxer** [comment]
I am currently talking with a company that offered to do the design (see #15) for the project and they looked at these Ideas. Let's see what they come up with.

**Comment by bitboxer** [comment]
Closing this now because it will be solved together with #15 .
