### ISSUE TITLE
Add "word" Datamodel

### ISSUE THREAD

**Issue by bitboxer** [signdict/website#35]
We have to discuss how we want to implement "words". See [the wiki](https://github.com/signdict/website/wiki/Datamodel) for a rough outline.

These problems need to be discussed before we do it:

* a language needs to be attached to the word, so we need to create that model, too. What should be in that model?
* Should we link between the german and the english word? if yes, how can we make this editable by users? Currently I think it would be an awesome feature, but too hard to do.

**Comment by bitboxer** [comment]
I think I will call it "entry" or something like that. It can contain a word, a phrase or later something else more complicated?

**Comment by EinLama** [comment]
Although `entry` seems ambiguous on first thought, I think it's fitting in this case. Since we are basically talking about dictionary entries :+1: 

A language model could contain fields for `language_code` and `dialect`, although I'm not sure if we are taking it too far when we add dialects to our data models... 🤔 It's easy to over-engineer here. What do you say?

As I understand it, sign language has many dialects in the same language, so a distinction might prove useful. We have to be careful to leave the frontend simple, though. Many users who want to help and upload videos with new signs could be unaware of dialects they might be using? 🤔

**Comment by bitboxer** [comment]
Yes, the dialect part is a bit problematic. I don't think we can force that decision to the user. Maybe we can do that with information like "where did you grew up", "where do you live"?. Adding that to the language model might be too hard for us now.

**Comment by bitboxer** [comment]
I will start working on this after lunch 🍽

**Comment by bitboxer** [comment]
I now created the following models: `entry` and `language`. These have `belongs_to` and `has_many` relations to `user` and `video`. Next up: adding backend views for this.

**Comment by bitboxer** [comment]
Closed with #51
